"""urls table

Revision ID: 213744de85a4
Revises: 591506d259b8
Create Date: 2023-02-08 17:42:11.090245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213744de85a4'
down_revision = '591506d259b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longurl', sa.String(), nullable=True),
    sa.Column('shorturl', sa.String(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_url_longurl'), ['longurl'], unique=True)
        batch_op.create_index(batch_op.f('ix_url_shorturl'), ['shorturl'], unique=True)
        batch_op.create_index(batch_op.f('ix_url_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_url_timestamp'))
        batch_op.drop_index(batch_op.f('ix_url_shorturl'))
        batch_op.drop_index(batch_op.f('ix_url_longurl'))

    op.drop_table('url')
    # ### end Alembic commands ###
