"""empty message

Revision ID: c073447f5d35
Revises: effc74533464
Create Date: 2023-02-13 14:46:31.601506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c073447f5d35'
down_revision = 'effc74533464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short', sa.String(length=8), nullable=False))
        batch_op.drop_index('ix_url_shorturl')
        batch_op.create_index(batch_op.f('ix_url_short'), ['short'], unique=True)
        batch_op.drop_column('shorturl')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shorturl', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_url_short'))
        batch_op.create_index('ix_url_shorturl', ['shorturl'], unique=False)
        batch_op.drop_column('short')

    # ### end Alembic commands ###
