"""empty message

Revision ID: dc8c0c96a8ae
Revises: 213744de85a4
Create Date: 2023-02-10 12:15:58.471252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8c0c96a8ae'
down_revision = '213744de85a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.alter_column('longurl',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('shorturl',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index('ix_url_longurl')
        batch_op.create_index(batch_op.f('ix_url_longurl'), ['longurl'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_url_longurl'))
        batch_op.create_index('ix_url_longurl', ['longurl'], unique=False)
        batch_op.alter_column('shorturl',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('longurl',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
