"""empty message

Revision ID: effc74533464
Revises: dc8c0c96a8ae
Create Date: 2023-02-13 14:38:07.191585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'effc74533464'
down_revision = 'dc8c0c96a8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clicks', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_url_clicks'), ['clicks'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_url_clicks'))
        batch_op.drop_column('clicks')

    # ### end Alembic commands ###
